### ISSUE TITLE
serialnumber - именование

### ISSUE THREAD

**Issue by algolGuru** [Artem-Cherkasov/TravelLine_Practice#10]
https://github.com/Artem-Cherkasov/TravelLine_Practice/blob/01589416d975ec1965f7482ed13fea011f3189f7/ProductShop/ShopLib/Product.cs#L12

**Comment by Artem-Cherkasov** [comment]
Исправлено: https://github.com/Artem-Cherkasov/TravelLine_Practice/commit/4708d4275071cd8fbf3c406115675d3688f50955#diff-bda2f0a1237ce5c884f73cd0c7b0099a5dc465b44319c24ae38c09c39dbc7574
