### ISSUE TITLE
почему toDouble ?

### ISSUE THREAD

**Issue by algolGuru** [Artem-Cherkasov/TravelLine_Practice#12]
https://github.com/Artem-Cherkasov/TravelLine_Practice/blob/01589416d975ec1965f7482ed13fea011f3189f7/ProductShop/ShopLib/Selling.cs#L30

**Comment by Artem-Cherkasov** [comment]
Исправлено: https://github.com/Artem-Cherkasov/TravelLine_Practice/commit/852737bb5ae8810559e616047ce4659d09e991e1#diff-bda2f0a1237ce5c884f73cd0c7b0099a5dc465b44319c24ae38c09c39dbc7574
