### ISSUE TITLE
в данном случае конвертировать не нужно

### ISSUE THREAD

**Issue by algolGuru** [Artem-Cherkasov/TravelLine_Practice#14]
https://github.com/Artem-Cherkasov/TravelLine_Practice/blob/01589416d975ec1965f7482ed13fea011f3189f7/ProductShop/ProductShop/Program.cs#L24

**Comment by Artem-Cherkasov** [comment]
Исправлено: https://github.com/Artem-Cherkasov/TravelLine_Practice/commit/3e2d442073b89be77614f1ae90e603ce0b651cfe#diff-bda2f0a1237ce5c884f73cd0c7b0099a5dc465b44319c24ae38c09c39dbc7574
