### ISSUE TITLE
Не знаю структуру таблицы, но есть предположение, что условии group by можно обойтись без name

### ISSUE THREAD

**Issue by algolGuru** [Artem-Cherkasov/TravelLine_Practice#15]
https://github.com/Artem-Cherkasov/TravelLine_Practice/blob/9960b232cbb7f463f4999e52225258991d63f55e/ShopDataBase/BlogApp/Program.cs#L43

**Comment by Artem-Cherkasov** [comment]
Без него выдаёт такую ошибку: "Столбец "Customer.Name" недопустим в списке выбора, поскольку он не содержится ни в агрегатной функции, ни в предложении GROUP BY".
