### ISSUE TITLE
Было бы неплохо сделать простые CRUD операции, такие как удаление, добавление и обновление таблицы

### ISSUE THREAD

**Issue by algolGuru** [Artem-Cherkasov/TravelLine_Practice#16]
https://github.com/Artem-Cherkasov/TravelLine_Practice/blob/9960b232cbb7f463f4999e52225258991d63f55e/ShopDataBase/BlogApp/Program.cs#L10

**Comment by Artem-Cherkasov** [comment]
Добавлено: https://github.com/Artem-Cherkasov/TravelLine_Practice/commit/9b48dd750c12b1a1dfa6a84c579cd6736c7b5d67#diff-27e9bc8cbe2737275445a7440f4355a62dedf634a2f46fca8fdaa42d03b30632
