### ISSUE TITLE
В конструкторе не должно быть вызова метода Print

### ISSUE THREAD

**Issue by algolGuru** [Artem-Cherkasov/TravelLine_Practice#3]
https://github.com/Artem-Cherkasov/TravelLine_Practice/blob/b8b5ed9b948b90baefb505fcd9bfbeeeacd33149/ProductShop/ShopLib/Product.cs#L16

**Comment by Artem-Cherkasov** [comment]
Исправлено: https://github.com/Artem-Cherkasov/TravelLine_Practice/commit/e33f9f150adb2fe030441b45660859bb786fca5b#diff-51c86b6867198e22e2ce3d2ecb3044718f216f5d6f4aba7b196354dc3a31f76f
