### ISSUE TITLE
Конструктор нужен для инициализации переменных

### ISSUE THREAD

**Issue by algolGuru** [Artem-Cherkasov/TravelLine_Practice#6]
https://github.com/Artem-Cherkasov/TravelLine_Practice/blob/b8b5ed9b948b90baefb505fcd9bfbeeeacd33149/ProductShop/ShopLib/Selling.cs#L17

**Comment by Artem-Cherkasov** [comment]
Исправлено: https://github.com/Artem-Cherkasov/TravelLine_Practice/commit/30a06c313b20bb78c3dd496b0309e842092b77f7#diff-51c86b6867198e22e2ce3d2ecb3044718f216f5d6f4aba7b196354dc3a31f76f

**Comment by Artem-Cherkasov** [comment]
Исправлено: https://github.com/Artem-Cherkasov/TravelLine_Practice/commit/06a6502f3c159bbded5c6644aa6bb7778c53f959#diff-51c86b6867198e22e2ce3d2ecb3044718f216f5d6f4aba7b196354dc3a31f76f
