### ISSUE TITLE
Слишком большая функция с дублированием кода

### ISSUE THREAD

**Issue by algolGuru** [Artem-Cherkasov/TravelLine_Practice#7]
https://github.com/Artem-Cherkasov/TravelLine_Practice/blob/b8b5ed9b948b90baefb505fcd9bfbeeeacd33149/ProductShop/ShopLib/Selling.cs#L22

**Comment by Artem-Cherkasov** [comment]
Не понимаю как можно исправить это условие

**Comment by Artem-Cherkasov** [comment]
Разделил Offer на несколько методов: https://github.com/Artem-Cherkasov/TravelLine_Practice/commit/6f48f909c7f0ad152290395c39d15183a61029dc#diff-c86253ef7258a04e422f22f5601d9c59dddc147e17cb7d0fcf5acbb9e9b30fb5;

Ссылка на изменения в программе: https://github.com/Artem-Cherkasov/TravelLine_Practice/commit/01589416d975ec1965f7482ed13fea011f3189f7#diff-6ef58a281301b32199d9bcb31b928687537fa9704145bf83455a3df83f9c2375
