### ISSUE TITLE
Конструктор не должен обращаться к потокам ввода

### ISSUE THREAD

**Issue by algolGuru** [Artem-Cherkasov/TravelLine_Practice#9]
https://github.com/Artem-Cherkasov/TravelLine_Practice/blob/01589416d975ec1965f7482ed13fea011f3189f7/ProductShop/ShopLib/Greetings.cs#L14

Конструктор не должен обращаться к потокам ввода, передайте в констурктор строку, которая будет инициализировать visitor, и перед тем как создавать объект, вы можете уже считать ввод и передать в конструктор

**Comment by Artem-Cherkasov** [comment]
Исправлено: https://github.com/Artem-Cherkasov/TravelLine_Practice/commit/6d237835c905faf17ec11bc9e1255f34c8b3898a#diff-bda2f0a1237ce5c884f73cd0c7b0099a5dc465b44319c24ae38c09c39dbc7574
